In [1]:
22+33

55

In [2]:
5-2

3

In [3]:
4//2

2

In [4]:
4/2

2.0

In [5]:
7%3

1

In [6]:
5*6

30

In [7]:
3+2
4+6

10

In [4]:
x=0
if(x>0):
    print("positive")
elif(x==0):
    print("zero")
else:
    print("negative")

zero

In [1]:
import matplotlib.animation as animation
print(animation.writers.list())

['pillow', 'html']

In [2]:
import pandas as pd
import os
os.getcwd()

'C:\\Users\\goela'

In [3]:
os.listdir(os.getcwd())

['.conda',
 '.condarc',
 '.ipynb_checkpoints',
 '.ipython',
 '.jupyter',
 '2018_Sales_Total_Tabs.xlsx',
 '3D Objects',
 'Anaconda3',
 'AppData',
 'Application Data',
 'bigmart_data.csv',
 'capitals.csv',
 'capitals.xlsx',
 'Contacts',
 'Cookies',
 'data.csv',
 'database.ipynb',
 'Desktop',
 'Documents',
 'Downloads',
 'Favorites',
 'IntelGraphicsProfiles',
 'Linear Regression.ipynb',
 'Links',
 'Local Settings',
 'MicrosoftEdgeBackups',
 'MSE.ipynb',
 'Music',
 'My Documents',
 'NetHood',
 'NTUSER.DAT',
 'ntuser.dat.LOG1',
 'ntuser.dat.LOG2',
 'NTUSER.DAT{703521e4-9dc1-11ea-a57a-80c9a67ed98b}.TxR.0.regtrans-ms',
 'NTUSER.DAT{703521e4-9dc1-11ea-a57a-80c9a67ed98b}.TxR.1.regtrans-ms',
 'NTUSER.DAT{703521e4-9dc1-11ea-a57a-80c9a67ed98b}.TxR.2.regtrans-ms',
 'NTUSER.DAT{703521e4-9dc1-11ea-a57a-80c9a67ed98b}.TxR.blf',
 'NTUSER.DAT{703521e5-9dc1-11ea-a57a-80c9a67ed98b}.TM.blf',
 'NTUSER.DAT{703521e5-9dc1-11ea-a57a-80c9a67ed98b}.TMContainer00000000000000000001.regtrans-ms',
 'NTUSER.DAT{703521e5-9dc1-11ea-a57a-80c9a67ed98b}.TMContainer00000000000000000002.regtrans-ms',
 'ntuser.ini',
 'OneDrive',
 'Pictures',
 'PrintHood',
 'Recent',
 'SampleData.csv',
 'SampleData.xlsx',
 'Saved Games',
 'scorpio.db',
 'Searches',
 'SendTo',
 'speech.mp3',
 'Start Menu',
 'Templates',
 'test.db',
 'Text to speech.ipynb',
 'Untitled.ipynb',
 'untitled.slx',
 'Untitled1.ipynb',
 'Untitled2.ipynb',
 'Untitled3.ipynb',
 'Videos']

In [5]:
pd.read_csv('bigmart_data.csv')

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.300,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.920,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.500,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.200,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800
4,NCD19,8.930,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052
...,...,...,...,...,...,...,...,...,...,...,...,...
8518,FDF22,6.865,Low Fat,0.056783,Snack Foods,214.5218,OUT013,1987,High,Tier 3,Supermarket Type1,2778.3834
8519,FDS36,8.380,Regular,0.046982,Baking Goods,108.1570,OUT045,2002,NaN,Tier 2,Supermarket Type1,549.2850
8520,NCJ29,10.600,Low Fat,0.035186,Health and Hygiene,85.1224,OUT035,2004,Small,Tier 2,Supermarket Type1,1193.1136
8521,FDN46,7.210,Regular,0.145221,Snack Foods,103.1332,OUT018,2009,Medium,Tier 3,Supermarket Type2,1845.5976
8522,DRG01,14.800,Low Fat,0.044878,Soft Drinks,75.4670,OUT046,1997,Small,Tier 1,Supermarket Type1,765.6700

In [6]:
pd.read_csv('C:\\Users\\goela\\bigmart_data.csv')

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.300,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.920,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.500,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.200,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800
4,NCD19,8.930,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052
...,...,...,...,...,...,...,...,...,...,...,...,...
8518,FDF22,6.865,Low Fat,0.056783,Snack Foods,214.5218,OUT013,1987,High,Tier 3,Supermarket Type1,2778.3834
8519,FDS36,8.380,Regular,0.046982,Baking Goods,108.1570,OUT045,2002,NaN,Tier 2,Supermarket Type1,549.2850
8520,NCJ29,10.600,Low Fat,0.035186,Health and Hygiene,85.1224,OUT035,2004,Small,Tier 2,Supermarket Type1,1193.1136
8521,FDN46,7.210,Regular,0.145221,Snack Foods,103.1332,OUT018,2009,Medium,Tier 3,Supermarket Type2,1845.5976
8522,DRG01,14.800,Low Fat,0.044878,Soft Drinks,75.4670,OUT046,1997,Small,Tier 1,Supermarket Type1,765.6700